name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:  # Optional: Trigger on pull request
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Unlock secrets
      uses: sliteteam/github-action-git-crypt-unlock@1.2.0
      env:
        GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: yarn
        cache-dependency-path: 'frontend/yarn.lock'

    # Build the React app
    - name: Build React App
      run: |
        cd frontend
        yarn install
        yarn build
        mkdir -p ../app/static/expense-tracker
        mv build/* ../app/static/expense-tracker

    # Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Extract short commit SHA
    - name: Set short commit SHA
      id: vars
      run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV


    - name: Get Unix Timestamp
      id: timestamp
      run: echo "ts=$(date +%s)" >> "$GITHUB_ENV"

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: app
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/expense-tracker:ts_${{ env.ts }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: app
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/expense-tracker:latest

    # # Build the Docker image
    # - name: Build Docker image
    #   run: |
    #     docker build -t ghcr.io/${{ github.repository_owner }}/expense-tracker:${{ env.SHORT_SHA }} app/
    #
    # # Push the Docker image to GitHub Container Registry
    # - name: Push Docker image
    #   run: |
    #     docker push ghcr.io/${{ github.repository_owner }}/expense-tracker:${{ env.SHORT_SHA }}
